---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: podcasts-service
    kind: node-js
    owner: zencastr
  name: podcasts-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: podcasts-service
    kind: node-js
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: podcasts-service
    kind: node-js
    owner: zencastr
  name: podcasts-service
spec:
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app: podcasts-service
      kind: node-js
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: podcasts-service
        kind: node-js
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - podcasts-service
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: APP_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: APP_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['env']
        - name: APP_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PORT
          value: "8080"
        image: sgrzemski/typecastr:0.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: app
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: podcasts-service
    kind: node-js
  name: podcasts-service
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: podcasts-service
      kind: node-js
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: podcasts-service
    kind: node-js
  name: podcasts-service
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podcasts-service
  targetCPUUtilizationPercentage: 75
